[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = { version = "0.6.3", default-features = false }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "day1"
harness = false

[[bench]]
name = "day2"
harness = false
